#!/bin/bash -e

if ! id | grep -q root; then
	echo "beagle-flasher-boot-emmc-rootfs-nvme must be run as root:"
	echo "sudo beagle-flasher-boot-emmc-rootfs-nvme"
	exit
fi

version_message="1.20240528.0, BeagleY-AI nvme with swap..."

#Debian 12, Ubuntu Lunar, Mantic, Noble
#https://packages.debian.org/source/bookworm/e2fsprogs
#e2fsprogs (1.47.0) added orphan_file first added in v5.15.x
unset ext4_options
ext4_options="-O ^orphan_file"

cylon_leds() {
	#ls /sys/class/leds/beaglebone\:green\:usr*
	#cat /sys/class/leds/beaglebone\:green\:usr*/trigger
	local leds_base=/sys/class/leds/beaglebone\:green\:usr
	if [ -e ${leds_base}0/trigger ] ; then
		echo none > ${leds_base}0/trigger || true
		echo none > ${leds_base}1/trigger || true
		echo none > ${leds_base}2/trigger || true
		echo none > ${leds_base}3/trigger || true

		STATE=1
		while : ; do
		case $STATE in
			1)
				echo 1 > ${leds_base}0/brightness || true
				echo 0 > ${leds_base}1/brightness || true
				STATE=2
				;;
			2)
				echo 1 > ${leds_base}1/brightness || true
				echo 0 > ${leds_base}0/brightness || true
				STATE=3
				;;
			3)
				echo 1 > ${leds_base}2/brightness || true
				echo 0 > ${leds_base}1/brightness || true
				STATE=4
				;;
			4)
				echo 1 > ${leds_base}3/brightness || true
				echo 0 > ${leds_base}2/brightness || true
				STATE=5
				;;
			5)
				echo 1 > ${leds_base}2/brightness || true
				echo 0 > ${leds_base}3/brightness || true
				STATE=6
				;;
			6)
				echo 1 > ${leds_base}1/brightness || true
				echo 0 > ${leds_base}2/brightness || true
				STATE=1
				;;
			*)
				echo 1 > ${leds_base}0/brightness || true
				echo 0 > ${leds_base}1/brightness || true
				STATE=2
				;;
		esac
		sleep 0.1
		done
	fi
}

reset_leds() {
	if [ "x${has_usr_leds}" = "xenable" ] ; then
		if [ -e /proc/$CYLON_PID ]; then
			kill $CYLON_PID > /dev/null 2>&1
		fi

		leds_pattern0=${leds_pattern0:-"heartbeat"}
		leds_pattern1=${leds_pattern1:-"mmc0"}
		leds_pattern2=${leds_pattern2:-"activity"}
		leds_pattern3=${leds_pattern3:-"mmc1"}
		leds_base=/sys/class/leds/beaglebone\:green\:usr

		if [ -e ${leds_base}0/trigger ] ; then
			echo ${leds_pattern0} > ${leds_base}0/trigger || true
			echo ${leds_pattern1} > ${leds_base}1/trigger || true
			echo ${leds_pattern2} > ${leds_base}2/trigger || true
			echo ${leds_pattern3} > ${leds_base}3/trigger || true
		fi
	fi
}

flush_cache () {
	sync
	if [ "x${destination}" != "x" ] ; then
		message="INFO: flush_cache: [blockdev --flushbufs ${destination}]"                         ; broadcast
		blockdev --flushbufs ${destination} || true
		message="--------------------------------------------------------------------------------" ; broadcast
	fi
}

broadcast () {
	if [ "x${message}" != "x" ] ; then
		echo "${message}"
		if [ "x${debug_over_display}" != "x" ] ; then
			echo "${message}" > /dev/${debug_over_display} || true
		fi
	fi
}

broadcast_over_display () {
	if [ "x${message}" != "x" ] ; then
		if [ "x${debug_over_display}" != "x" ] ; then
			echo "${message}" > /dev/${debug_over_display} || true
		fi
	fi
}

example_failure () {
	message="Example: /etc/default/beagle-flasher"                                             ; broadcast
	message="--------------------------------------------------------------------------------" ; broadcast
	message="source=/dev/mmcblk0"                                                              ; broadcast
	message="destination=/dev/mmcblk1"                                                         ; broadcast
	message="rfs_partition=dual"                                                               ; broadcast
	message="rfs_boot_startmb=1"                                                               ; broadcast
	message="rfs_boot_size_mb=256"                                                             ; broadcast
	message="bootloader=/opt/u-boot/bb-u-boot-beagleboneai64/install-emmc.sh"                  ; broadcast
	message="flash_back=bbai64-emmc-to-microsd"                                                ; broadcast
	message="extlinux=/opt/u-boot/bb-u-boot-beagleboneai64/emmc-extlinux.conf"                 ; broadcast
	message="--------------------------------------------------------------------------------" ; broadcast
	exit 2
}

write_failure () {
	message="ERROR: writing to [destination=${destination}] failed..."                         ; broadcast

	if [ "x${has_usr_leds}" = "xenable" ] ; then
		if [ -e /proc/$CYLON_PID ]; then
			kill $CYLON_PID > /dev/null 2>&1
		fi

		leds_pattern0=${leds_pattern0:-"heartbeat"}
		leds_pattern1=${leds_pattern1:-"heartbeat"}
		leds_pattern2=${leds_pattern2:-"heartbeat"}
		leds_pattern3=${leds_pattern3:-"heartbeat"}
		leds_base=/sys/class/leds/beaglebone\:green\:usr

		if [ -e ${leds_base}0/trigger ] ; then
			echo ${leds_pattern0} > ${leds_base}0/trigger || true
			echo ${leds_pattern1} > ${leds_base}1/trigger || true
			echo ${leds_pattern2} > ${leds_base}2/trigger || true
			echo ${leds_pattern3} > ${leds_base}3/trigger || true
		fi
		message="Debug: Setting Heartbeat"                                                         ; broadcast
	fi

	message="--------------------------------------------------------------------------------" ; broadcast
	flush_cache
	if [ "x${destination}" != "x" ] ; then
		umount ${destination}p1 > /dev/null 2>&1 || true
	fi
}

check_running_system () {

	message="INFO: /proc/cmdline"                                                              ; broadcast
	message="INFO: [cat /proc/cmdline]"                                                        ; broadcast
	cat /proc/cmdline
	message="--------------------------------------------------------------------------------" ; broadcast

	has_usr_leds="enable"

	if [ "x${has_usr_leds}" = "xenable" ] ; then
		cylon_leds & CYLON_PID=$!
	fi

	if [ "x${source}" != "x" ] && [ "x${destination}" != "x" ] ; then
		message="INFO: [lsblk -i]"                                                                 ; broadcast
		message="`lsblk -i || true`"                                                               ; broadcast
		message="--------------------------------------------------------------------------------" ; broadcast
		message="INFO: copying [${source}] -> [${destination}]"                                    ; broadcast
		message="--------------------------------------------------------------------------------" ; broadcast
	else
		message="INFO: [lsblk -i]"                                                                 ; broadcast
		message="`lsblk -i || true`"                                                               ; broadcast
		message="--------------------------------------------------------------------------------" ; broadcast
		message="ERROR: Setup: [source] and [destination] in /etc/default/beagle-flasher"          ; broadcast
		message="--------------------------------------------------------------------------------" ; broadcast
		example_failure
	fi

	if [ ! -b "${source}" ] ; then
		message="ERROR: [source=${source}] does not exist"                                         ; broadcast
		message="--------------------------------------------------------------------------------" ; broadcast
		example_failure
	else
		message="INFO: [source=${source}] is a valid block device"                                 ; broadcast
	fi

	if [ ! -b "${destination}" ] ; then
		message="ERROR: [destination=${destination}] does not exist"                               ; broadcast
		message="--------------------------------------------------------------------------------" ; broadcast
		example_failure
	else
		message="INFO: [destination=${destination}] is a valid block device"                       ; broadcast
	fi

	if [ ! -f /boot/config-$(uname -r) ] ; then
		zcat /proc/config.gz > /boot/config-$(uname -r) || true
		message="INFO: Creating: [/boot/config-$(uname -r)]"                                       ; broadcast
	else
		message="INFO: [/boot/config-$(uname -r)]"                                                 ; broadcast
	fi

	if [ -f /usr/sbin/update-initramfs ] ; then
		message="INFO: Generating: [/boot/initrd.img-$(uname -r)]"                                         ; broadcast
		message="update-initramfs: Generating /boot/initrd.img-$(uname -r)"                                ; broadcast_over_display
		if [ -f /boot/initrd.img-$(uname -r) ] ; then
			update-initramfs -u -k $(uname -r) || true
			message="--------------------------------------------------------------------------------" ; broadcast
		else
			update-initramfs -c -k $(uname -r) || true
			message="--------------------------------------------------------------------------------" ; broadcast
		fi
		if [ -f /boot/firmware/initrd.img ] ; then
			cp -v /boot/initrd.img-$(uname -r) /boot/firmware/initrd.img
		fi
	fi
	flush_cache

	if [ -f /etc/default/generic-sys-mods ] ; then
		message="INFO: [cat /etc/default/generic-sys-mods]"                             ; broadcast
		cat /etc/default/generic-sys-mods
		. /etc/default/generic-sys-mods
		src_rfs_part=${ROOT_PARTITION}
		message="--------------------------------------------------------------------------------" ; broadcast
	fi
}

format_boot () {
	message="mkfs.vfat -F 16 ${destination}p1 -n ${boot_label}"                          ; broadcast
	LC_ALL=C mkfs.vfat -F 16 ${destination}p1 -n ${boot_label}
	message="--------------------------------------------------------------------------------" ; broadcast
	flush_cache
}

format_root () {
	message="mkfs.ext4 ${ext4_options} ${destination}p${dest_rfs_part} -L ${rootfs_label}"              ; broadcast
	LC_ALL=C mkfs.ext4 ${ext4_options} ${destination}p${dest_rfs_part} -L ${rootfs_label}
	message="--------------------------------------------------------------------------------" ; broadcast
	flush_cache
}

format_single_root () {
	message="mkfs.ext4 ${ext4_options} ${destination}p1 -L ${single_root_label}"         ; broadcast
	LC_ALL=C mkfs.ext4 ${ext4_options} ${destination}p1 -L ${single_root_label}
	message="--------------------------------------------------------------------------------" ; broadcast
	flush_cache
}

copy_boot_extlinux () {
	message="Updating extlinux.conf" ; broadcast

	if [ -f ${extlinux} ] ; then
		message="INFO: [/boot/extlinux/extlinux.conf]"                                             ; broadcast
		cp -v ${extlinux} /boot/extlinux/extlinux.conf
		message="INFO: [cat /boot/extlinux/extlinux.conf]"                                     ; broadcast
		message="`cat /boot/extlinux/extlinux.conf`"                                           ; broadcast
		message="--------------------------------------------------------------------------------" ; broadcast
	fi
	flush_cache
}

copy_rootfs () {
	message="INFO: Copying: ${source}p${src_rfs_part} -> ${destination}p${dest_rfs_part}"       ; broadcast
	mkdir -p /tmp/rootfs/ || true

	message="INFO: [mount ${destination}p${dest_rfs_part} /tmp/rootfs/ -o async,noatime]"       ; broadcast
	mount ${destination}p${dest_rfs_part} /tmp/rootfs/ -o async,noatime

	message="INFO: rsync: (-aHAXx) [/ -> /tmp/rootfs/]"                                ; broadcast
	rsync -aHAXx --human-readable --info=progress2 /* /tmp/rootfs/ --exclude={/dev/*,/proc/*,/sys/*,/tmp/*,/run/*,/mnt/*,/media/*,/lost+found,/lib/modules/*,/boot/firmware/*} || write_failure
	message="--------------------------------------------------------------------------------" ; broadcast
	flush_cache

	message="INFO: rsync: (-aHAXx) [/ -> /tmp/rootfs/]"                                ; broadcast
	rsync -aHAXx --human-readable --info=progress2 /* /tmp/rootfs/ --exclude={/dev/*,/proc/*,/sys/*,/tmp/*,/run/*,/mnt/*,/media/*,/lost+found,/lib/modules/*,/boot/firmware/*} || write_failure
	message="--------------------------------------------------------------------------------" ; broadcast
	flush_cache

	message="INFO: Copying: Kernel modules"                                                    ; broadcast
	mkdir -p /tmp/rootfs/lib/modules/$(uname -r)/ || true
	message="INFO: rsync: (-aHAXx) /lib/modules/$(uname -r)/ -> /tmp/rootfs/lib/modules/$(uname -r)/" ; broadcast
	rsync -aHAXx --human-readable --info=progress2 /lib/modules/$(uname -r)/* /tmp/rootfs/lib/modules/$(uname -r)/ || write_failure
	message="--------------------------------------------------------------------------------" ; broadcast
	flush_cache

	message="INFO: Generating: /etc/fstab"                                                     ;  broadcast
	echo "# /etc/fstab: static file system information." > /tmp/rootfs/etc/fstab
	echo "#" >> /tmp/rootfs/etc/fstab
	echo "${destination}p${dest_rfs_part}  /  ext4  noatime,errors=remount-ro  0  1" >> /tmp/rootfs/etc/fstab
	echo "${source}p1  /boot/firmware vfat ${rfs_boot_permissions} 0 0" >> /tmp/rootfs/etc/fstab
	if [ "x${rfs_swap_size_mb}" != "x" ] ; then
		echo "${destination}p1  none    swap    sw      0       0" >>/tmp/rootfs/etc/fstab
	fi
	echo "debugfs  /sys/kernel/debug  debugfs  mode=755,uid=root,gid=gpio,defaults  0  0" >> /tmp/rootfs/etc/fstab
	message="INFO: [cat /tmp/rootfs/etc/fstab]"                                                ; broadcast
	message="`cat /tmp/rootfs/etc/fstab`"                                                      ; broadcast
	message="--------------------------------------------------------------------------------" ; broadcast
	flush_cache

	if [ -f /tmp/rootfs/etc/systemd/system/multi-user.target.wants/grow_partition.service ] ; then
		rm -rf /tmp/rootfs/etc/systemd/system/multi-user.target.wants/grow_partition.service || true
	fi
	flush_cache

	message="Copying: ${source}p${src_rfs_part} -> ${destination}p${dest_rfs_part} complete"    ; broadcast
	message="--------------------------------------------------------------------------------" ; broadcast
	flush_cache

	message="INFO: [umount /tmp/rootfs/ || umount -l /tmp/rootfs/ || write_failure]"           ; broadcast
	umount /tmp/rootfs/ || umount -l /tmp/rootfs/ || write_failure
	message="--------------------------------------------------------------------------------" ; broadcast

	message="INFO: Force writeback of eMMC buffers by Syncing: ${destination}"                 ; broadcast
	message="INFO: [dd if=${destination} of=/dev/null count=100000 status=progress]"           ; broadcast
	dd if=${destination} of=/dev/null count=100000 status=progress
	message="--------------------------------------------------------------------------------" ; broadcast
	flush_cache

	if [ "x${has_usr_leds}" = "xenable" ] ; then
		reset_leds
	fi
}

partition_drive () {
	message="INFO: Erasing: [${destination}]"                                                  ; broadcast
	flush_cache
	message="INFO: [dd if=/dev/zero of=${destination} bs=1M count=148 status=progress]"        ; broadcast
	dd if=/dev/zero of=${destination} bs=1M count=148 status=progress
	message="--------------------------------------------------------------------------------" ; broadcast
	sync
	message="INFO: [dd if=${destination} of=/dev/null bs=1M count=148 status=progress]"        ; broadcast
	dd if=${destination} of=/dev/null bs=1M count=148 status=progress
	message="--------------------------------------------------------------------------------" ; broadcast
	sync
	flush_cache
	message="INFO: Erasing: [${destination}] complete"                                         ; broadcast
	message="--------------------------------------------------------------------------------" ; broadcast

	if [ "x${bootloader}" != "x" ] ; then
		if [ -f ${bootloader} ] ; then
			message="INFO: [/bin/bash ${bootloader}]"                                                  ; broadcast
			/bin/bash ${bootloader}
			message="--------------------------------------------------------------------------------" ; broadcast
		fi
	fi

	rfs_boot_permissions=${rfs_boot_permissions:-"defaults"}

	if [ "x${rfs_partition}" = "xhybrid" ] ; then
		partition_one_start_mb=${rfs_rootfs_startmb:-"1"}
		partition_one_fstype=${rfs_sfdisk_fstype:-"L"}

		single_root_label=${single_root_label:-"rootfs"}

		sfdisk_options="--force --wipe-partitions always"

		message="INFO: Partitioning: ${destination}"                                               ; broadcast
		message="INFO: sfdisk: [$(LC_ALL=C sfdisk --version)]"                         ; broadcast
		message="INFO: sfdisk: [sfdisk ${sfdisk_options} ${destination}]"              ; broadcast
		message="INFO: sfdisk: [${partition_one_start_mb}M,,${partition_one_fstype},*]"                 ; broadcast
		message="--------------------------------------------------------------------------------" ; broadcast

		LC_ALL=C sfdisk ${sfdisk_options} "${destination}" <<-__EOF__
			${partition_one_start_mb}M,,${partition_one_fstype},*
		__EOF__

		flush_cache
		message="INFO: Formatting: ${destination}"                                                 ; broadcast
		format_single_root
		message="INFO: Formatting: ${destination} complete"                                        ; broadcast
		message="--------------------------------------------------------------------------------" ; broadcast

		if [ "x${rfs_swap_size_mb}" != "x" ] ; then
			src_rfs_part=${src_rfs_part:-"3"}
			dest_rfs_part="1"
		else
			src_rfs_part=${src_rfs_part:-"2"}
			dest_rfs_part="1"
		fi
		copy_boot_extlinux
		copy_rootfs
	elif [ "x${rfs_partition}" = "xhybrid_swap" ] ; then
		partition_one_start_mb=${rfs_boot_startmb:-"1"}
		partition_one_size_mb="${rfs_swap_size_mb}"
		partition_one_fstype=${rfs_sfdisk_fstype:-"0x82"}

		partition_two_start_mb=$(($partition_one_start_mb + $partition_one_size_mb))

		rootfs_label=${rootfs_label:-"rootfs"}
		sfdisk_options="--force --wipe-partitions always"

		message="INFO: Partitioning: ${destination}"                                               ; broadcast
		message="INFO: sfdisk: [$(LC_ALL=C sfdisk --version)]"                         ; broadcast
		message="INFO: sfdisk: [sfdisk ${sfdisk_options} ${destination}]"              ; broadcast
		message="INFO: sfdisk: [${partition_one_start_mb}M,${partition_one_size_mb}M,${partition_one_fstype},-]" ; broadcast
		message="INFO: sfdisk: [${partition_two_start_mb}M,,,-]" ; broadcast
		message="--------------------------------------------------------------------------------" ; broadcast

		LC_ALL=C sfdisk ${sfdisk_options} "${destination}" <<-__EOF__
			${partition_one_start_mb}M,${partition_one_size_mb}M,${partition_one_fstype},-
			${partition_two_start_mb}M,,,-
		__EOF__

		flush_cache

		flush_cache
		message="INFO: Formatting: ${destination}"                                                 ; broadcast
		format_single_root
		message="INFO: Formatting: ${destination} complete"                                        ; broadcast
		message="--------------------------------------------------------------------------------" ; broadcast

		src_rfs_part=${src_rfs_part:-"3"}
		dest_rfs_part="2"

		message="INFO: Formatting: ${destination}"                                                 ; broadcast
		format_root
		LC_ALL=C mkswap ${destination}p1
		message="INFO: Formatting: ${destination} complete"                                        ; broadcast
		message="--------------------------------------------------------------------------------" ; broadcast

		copy_boot_extlinux
		copy_rootfs
	elif [ "x${rfs_partition}" = "xdual" ] ; then
		partition_one_start_mb=${rfs_boot_startmb:-"1"}
		partition_one_size_mb=${rfs_boot_size_mb:-"256"}
		partition_one_fstype=${rfs_sfdisk_fstype:-"0xc"}

		partition_two_start_mb=$(($partition_one_start_mb + $partition_one_size_mb))

		if [ "x${rfs_swap_size_mb}" != "x" ] ; then
			partition_two_size_mb="${rfs_swap_size_mb}"
			partition_three_start_mb=$(($partition_one_start_mb + $partition_one_size_mb + $partition_two_size_mb))
		fi

		boot_label=${boot_label:-"FIRMWARE"}
		rootfs_label=${rootfs_label:-"rootfs"}

		sfdisk_options="--force --wipe-partitions always"

		message="INFO: Partitioning: ${destination}"                                               ; broadcast
		message="INFO: sfdisk: [$(LC_ALL=C sfdisk --version)]"                         ; broadcast
		message="INFO: sfdisk: [sfdisk ${sfdisk_options} ${destination}]"              ; broadcast
		message="INFO: sfdisk: [${partition_one_start_mb}M,${partition_one_size_mb}M,${partition_one_fstype},*]" ; broadcast
		if [ "x${rfs_swap_size_mb}" != "x" ] ; then
			message="INFO: sfdisk: [${partition_two_start_mb}M,${partition_two_size_mb}M,0x82,-]" ; broadcast
			message="INFO: sfdisk: [${partition_three_start_mb}M,,,-]" ; broadcast
		else
			message="INFO: sfdisk: [${partition_two_start_mb}M,,,-]" ; broadcast
		fi
		message="--------------------------------------------------------------------------------" ; broadcast

		if [ "x${rfs_swap_size_mb}" != "x" ] ; then
			LC_ALL=C sfdisk ${sfdisk_options} "${destination}" <<-__EOF__
				${partition_one_start_mb}M,${partition_one_size_mb}M,${partition_one_fstype},*
				${partition_two_start_mb}M,${partition_two_size_mb}M,0x82,-
				${partition_three_start_mb}M,,,-
			__EOF__
		else
			LC_ALL=C sfdisk ${sfdisk_options} "${destination}" <<-__EOF__
				${partition_one_start_mb}M,${partition_one_size_mb}M,${partition_one_fstype},*
				${partition_two_start_mb}M,,,-
			__EOF__
		fi

		flush_cache

		if [ "x${rfs_swap_size_mb}" != "x" ] ; then
			src_rfs_part=${src_rfs_part:-"3"}
			dest_rfs_part="3"
		else
			src_rfs_part=${src_rfs_part:-"2"}
			dest_rfs_part="2"
		fi

		message="INFO: Formatting: ${destination}"                                                 ; broadcast
		format_boot
		format_root
		if [ "x${rfs_swap_size_mb}" != "x" ] ; then
			LC_ALL=C mkswap ${destination}p2
		fi
		message="INFO: Formatting: ${destination} complete"                                        ; broadcast
		message="--------------------------------------------------------------------------------" ; broadcast

		copy_boot
		copy_rootfs
	else
		example_failure
	fi
}

###FIXME
if [ -f /etc/default/beagle-flasher ] ; then
	. /etc/default/beagle-flasher
	message="--------------------------------------------------------------------------------" ; broadcast
	message="Version: [${version_message}]" ; broadcast
	message="--------------------------------------------------------------------------------" ; broadcast
	message="cat /etc/default/beagle-flasher:"                                                 ; broadcast
	message="--------------------------------------------------------------------------------" ; broadcast
	message="`cat /etc/default/beagle-flasher`"                                                ; broadcast
	message="--------------------------------------------------------------------------------" ; broadcast
else
	message="--------------------------------------------------------------------------------" ; broadcast
	message="Version: [${version_message}]"                                                    ; broadcast
	message="--------------------------------------------------------------------------------" ; broadcast
	example_failure
fi

check_running_system
partition_drive
