#!/bin/sh

if [ -f /etc/default/generic-sys-mods ] ; then
	. /etc/default/generic-sys-mods
fi

if [ ! "x${ROOT_DRIVE}" = "x" ] ; then
	if [ ! "x${ROOT_PARTITION}" = "x" ] ; then
		echo "growpart -v ${ROOT_DRIVE} ${ROOT_PARTITION}"
		growpart -v ${ROOT_DRIVE} ${ROOT_PARTITION} || true
		if [ -f /etc/bbb.io/growpart ] ; then
			rm -rf /etc/bbb.io/growpart || true
			sync
		fi
		touch /etc/bbb.io/growpart_done || true
		sync
	fi
fi
